apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: windows11-vm-disk
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 56Gi
  storageClassName: gp2  # e.g., "standard" or "hostpath-provisioner"
  volumeMode: Block
